sample-url: https://github.com/RayyanMasood/msbdb/releases/download/v1.0.0/MSBDB24_wav_stems.zip

# global dataset samplerate
sample_rate: 44100.0

# Define the Input sources for each track
sources:
  speech: Speech.wav
  music: Music.wav
  background: Background.wav

# Additionally provide the artistic mix
mixture: Mixed.wav

stem_ids:
  mixture: 0
  speech: 1
  background: 2
  music: 3

# Define output targets to be tested using linear mixtures
targets:
  speech:
    speech: 1
  background:
    background: 1
  music:
    music: 1
  accompaniment:
    speech: 1
    background: 1
  linear_mixture:
    music: 1
    background: 1
    speech: 1

validation_tracks:
- 'final_output_0'
- 'final_output_17'
- 'final_output_19'
- 'final_output_32'
- 'final_output_47'
- 'final_output_53'
- 'final_output_64'
- 'final_output_69'
- 'final_output_76'
- 'final_output_99'
- 'final_output_146'
- 'James May - On The Line'
- 'Meaxic - Take A Step'
- 'Traffic Experiment - Sirens'
